CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE post (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    alias VARCHAR(50) NOT NULL,
    mail VARCHAR(255),
    sexo VARCHAR(50) NOT NULL,
    categ VARCHAR(255) NOT NULL,
    comments VARCHAR(255) NOT NULL
);